  spec: 
    matchLabels:
      app: accounts
  stategy: {}
  template:
    metadata: 
      creationTimestamp: null
      labels : 
        app: accounts
    spec: 
      containers:
      - image: us.icr.io/sn-labs-supriyamish3/accounts: 1
        name: accounts
        resources: {}
        env:
          - name: DATABASE_HOST
            value: postgresql
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-name
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-password
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-user
                
